version: "2"
services:

  db:
    image: mariadb
    container_name: mariadb
    ports:
      - "7006:3306"
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    command: --init-file /data/application/init-script.sql
    volumes:
      - "${INFRASTRUCTURE_ROOT}/mariadb/init-script.sql:/data/application/init-script.sql"
    restart: unless-stopped
